name: Email Diario de Mercados
on:
  schedule:
    - cron: '0 7 * * 1-5'
    - cron: '0 8 * * 1-5'
  workflow_dispatch:
jobs:
  enviar-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4
      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: pip install yfinance pandas requests
      - name: Enviar email diario
        env:
          EMAIL_REMITENTE: ${{ secrets.EMAIL_REMITENTE }}
          EMAIL_PASSWORD:  ${{ secrets.EMAIL_PASSWORD }}
        run: python email_sender.py
